components:
  frontendProxy:
    service:
      type: LoadBalancer

opentelemetry-collector:
  config:
    exporters:
      otlp/traces:
        endpoint: kube-otel-stack-traces-collector:4317
        tls:
          insecure: true
      otlp/metrics:
        endpoint: kube-otel-stack-metrics-collector:4317
        tls:
          insecure: true
      elasticsearch: 
        endpoints: [https://logingest.lightstep.com:443]
        index: "lightstep"
        headers:
          lightstep-access-token: ${LS_TOKEN}
    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging, otlp/metrics]
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging, otlp/traces]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging, elasticsearch]